# Colonizer example verify ID file for KVM/QEMU (test lab) deployment
#
- hosts: all
  become: yes
  vars:
    ignore_disk_names: ["vda", "sda"]
  tasks:
    - set_fact:
        ansdev: "{{ ansdev | default('[]') }} + [ '{{ item }}' ]"
      with_items: "{{ ansible_devices.keys() }}"
      # Ignore device mapper entries
      when: not item | search('dm-')
    - assert:
        that: 
          - ansible_processor_vcpus == 2
            #- ansible_product_version == 'pc-i440fx-2.9'
          - ansible_memtotal_mb >= 992
          - ansible_architecture == 'x86_64'
          - ansible_system_vendor == 'QEMU'
          - ansible_distribution == 'RedHat'
          - ansible_distribution_major_version == '7'
          - (ansdev|length) == 4

    - name: check if disk sizes and naming is as expected
      with_items: "{{ (ansdev | difference(ignore_disk_names)) }}"
      assert:
        that:
          - ansible_devices[item]['size'] == '200.00 GB'
          - item.startswith('vd')

    # Depends on presence of package python-dnf
    - name: Install dependency for ansible selinux management
      package:
        name: libselinux-python.x86_64
        state: present

    - selinux:
        policy: targeted
        state: enforcing
