- shell: /bin/bash -c 'echo "Configuring chrony NTP..." > {{ fifo }}'

- name: Stop chronyd Service
  service:
    name: chronyd
    state: stopped

- name: Disable public NTP servers
  replace:
    dest: /etc/chrony.conf
    regexp: '^(server.*)'
    replace: '#\1'
  when: update_ntp == True

- name: Add custom NTP servers
  lineinfile:
    dest: /etc/chrony.conf
    insertafter: '^#server'
    line: 'server {{ item }} iburst'
    state: present
  with_items: '{{ ntpServers }}'
  when: update_ntp == True

- name: Start chronyd Service
  service:
    name: chronyd
    state: started

- name: Enable chronyd Service
  service:
    name: chronyd
    enabled: yes

- name: Force immediate time sync
  shell: /bin/chronyc makestep
