---
- name: Set CTDB lock volume name
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  set_fact:
    ctdb_volname: ctdb

- name: Set CTDB brick path
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  set_fact:
    ctdb_brick_path: /gluster/bricks/{{ ctdb_volname }}

- name: Build brick string for CTDB lock volume
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  set_fact:
    ctdb_brickstring: "{{ ctdb_brickstring | default('') }},{{ item }}:{{ ctdb_brick_path }}/{{ ctdb_volname }}"
  with_items:
    - "{{ ha_cluster_nodes.split(',') }}"

#== DISABLED DUE TO SMALL FILE PERFORMANCE PROBLEMS
# Convert SMB exports from libgfap to FUSE re-exports
#See https://access.redhat.com/solutions/2969381
#- shell: /bin/bash -c 'echo "Disabling Samba hook scripts..." > {{ fifo }}'
#
#- name: Set base hook path
#  set_fact:
#    hookpath: /var/lib/glusterd/hooks/1
#
#- name: Disable Gluster Samba hook scripts
#  command: mv {{ hookpath }}/{{ item.0 }}/{{ item.1 }} {{ hookpath }}/{{ item.0 }}/disabled-{{ item.1 }}
#  with_together:
#    - - set/post
#      - start/post
#      - stop/pre
#    - - S30samba-set.sh
#      - S30samba-start.sh
#      - S30samba-stop.sh
#
#== DISABLED DUE TO SMALL FILE PERFORMANCE PROBLEMS

- name: Start default volume
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  volume: 
    action: start
    volume: "{{ item }}"
    force: "{{ force | default(False) }}"
  with_items:
    - "{{ default_volname }}"
  register: result
  failed_when: "result.rc != 0 and ('already started' not in result.msg)"

#== DISABLED DUE TO SMALL FILE PERFORMANCE PROBLEMS
#
#- shell: /bin/bash -c 'echo "Mounting default volume locally..." > {{ fifo }}'
#
#- name: Set default volume mount path
#  set_fact:
#    default_vol_mountpoint: "/gluster/mount/{{ default_volname }}"
#
#- name: Create the default volume mount point, skips if present
#  file:
#    path: "{{ default_vol_mountpoint }}"
#    state: directory
#
#- name: Mount the default volume with FUSE
#  mount:
#    name: "{{ default_vol_mountpoint }}"
#    src: "{{ mount_host }}:/{{ default_volname }}"
#    fstype: glusterfs
#    opts: "{{ fuse_mount_opts }}"
#    state: mounted
#
#- name: Set SELinux boolean for samba_share_fusefs
#  seboolean:
#    name: samba_share_fusefs
#    state: on
#    persistent: yes
#
#- shell: /bin/bash -c 'echo "Adding default volume export to smb.conf..." > {{ fifo }}'
#
#- name: Add default volume export to smb.conf
#  lineinfile:
#    dest: /etc/samba/smb.conf
#    state: present
#    insertafter: EOF
#    line: "{{ item }}"
#  with_items:
#    - ""
#    - "# Auto-configured by gluster-one"
#    - "[{{ default_volname }}]"
#    - "        comment = For samba share of volume {{ default_volname }}"
#    - "        path = {{ default_vol_mountpoint }}"
#    - "        read only = no"
#    - "        guest ok = yes"
#== DISABLED DUE TO SMALL FILE PERFORMANCE PROBLEMS

- shell: /bin/bash -c 'echo "Configuring firewall for CTDB..." > {{ fifo }}'

- name: Open firewalld ports for CTDB
  firewalld:
    port: "{{ item }}"
    permanent: True
    immediate: True
    state: enabled
  with_items:
    - 4379/tcp

- shell: /bin/bash -c 'echo "Creating thin LV for CTDB lock volume..." > {{ fifo }}'

- name: Create CTDB logical volumes on first thin pool and volume group
  lv:
    action: create
    lvtype: thinlv
    poolname: "{{ backend_configuration.0.tp }}"
    vgname: "{{ backend_configuration.0.vg }}"
    lvname: "{{ ctdb_volname }}"
    virtualsize: "{{ dalign | default('128') }}M"

- shell: /bin/bash -c 'echo "Creating and mounting CTDB lock volume file systems..." > {{ fifo }}'

- name: Create CTDB XFS filesystems
  filesystem:
    fstype: xfs
    dev: /dev/{{ backend_configuration.0.vg }}/{{ ctdb_volname }}
    opts: "-f -i size=512 -n size=8192 -d su={{ dalign }}k,sw={{ diskcount }}"

- name: Create the CTDB brick mount points, skips if present
  file:
    path: "{{ ctdb_brick_path }}"
    state: directory

- name: Mount the CTDB filesystems
  mount:
    name: "{{ ctdb_brick_path }}"
    src: /dev/{{ backend_configuration.0.vg }}/{{ ctdb_volname }}
    fstype: xfs
    opts: "inode64,noatime,nodiratime"
    state: mounted

- name: Set the CTDB mount SELinux context
  file:
    path: "{{ ctdb_brick_path }}"
    setype: glusterd_brick_t

- shell: /bin/bash -c 'echo "Creating CTDB lock Gluster volume..." > {{ fifo }}'

- name: Create Gluster volume for CTDB lock
  delegate_to: 127.0.0.1
  run_once: true
  volume:
    action:         create
    volume:         "{{ ctdb_volname }}"
    bricks:         "{{ ctdb_brickstring }}"
    hosts:          "{{ play_hosts }}"
    replica:        yes
    # Below values need to be quoted as they are appended to the command line
    replica_count:  "{{ ctdb_replica_count }}"
    arbiter_count:  0
    force:          "{{ force | default(False) }}"
  register: result
  failed_when: "result.rc != 0 and ('already exists' not in result.msg)"

- shell: /bin/bash -c 'echo "Configuring CTDB and Samba..." > {{ fifo }}'

- name: Add volume name to ctdb setup/teardown scripts
  replace:
    dest: "{{ item }}"
    regexp: '^META="?all"?'
    replace: 'META="{{ ctdb_volname }}"'
  with_items:
    - /var/lib/glusterd/hooks/1/stop/pre/S29CTDB-teardown.sh
    - /var/lib/glusterd/hooks/1/start/post/S29CTDBsetup.sh
  ignore_errors: true

- name: Enable clustering in Samba
  lineinfile:
    dest: /etc/samba/smb.conf
    line: "clustering = yes"
    insertafter: '^\[global\]'

- name: Start CTDB lock volume
  delegate_to: 127.0.0.1
  run_once: true
  volume:
    action: start
    volume: "{{ item }}"
    force: "{{ force | default(False) }}"
  with_items:
    - "{{ ctdb_volname }}"
  register: result
  failed_when: "result.rc != 0 and ('already started' not in result.msg)"

- name: Clean up /etc/ctdb/nodes
  file:
    path: /etc/ctdb/nodes
    state: absent

- name: Clean /etc/ctdb/public_addresses
  file:
    path: /etc/ctdb/public_addresses
    state: absent

- name: Create /etc/ctdb/nodes
  file:
    path: /etc/ctdb/nodes
    state: touch

- name: Create /etc/ctdb/public_addresses
  file:
    path: /etc/ctdb/public_addresses
    state: touch

- name: Add HA node IPs to /etc/ctdb/nodes
  lineinfile:
    dest: /etc/ctdb/nodes
    line: "{{ item }}"
  with_items:
    - "{{ ha_cluster_nodes.split(',') }}"

- name: Add VIPs to /etc/ctdb/public_addresses
  lineinfile:
    dest: /etc/ctdb/public_addresses
    line: "{{ item }}/{{ storage_subnet_prefix }} {{ storage_interface }}"
  with_items:
    - "{{ vips }}"

- shell: /bin/bash -c 'echo "Starting CTDB..." > {{ fifo }}'

- name: Start ctdb service
  service:
    name: ctdb
    state: started

- shell: /bin/bash -c 'echo "Tuning default volume for Samba..." > {{ fifo }}'

- name: Set Gluster volume parameters for SMB
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true
  volume_set:
    action: set
    volume: "{{ default_volname }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:  "{{ gluster_vol_set_smb }}"

- shell: /bin/bash -c 'echo "Configuring and restarting glusterd..." > {{ fifo }}'

- name: Configure glusterd for insecure ports
  lineinfile:
      dest: /etc/glusterfs/glusterd.vol
      line: "    option rpc-auth-allow-insecure on"
      insertbefore: 'end-volume'

- name: Restart glusterd services
  service:
    name: glusterd
    state: restarted
